apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-qa
  namespace: qa
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 250m
        memory: 256Mi
      default:
        cpu: 1
        memory: 1Gi
      max:
        cpu: "4"
        memory: 8Gi
