apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dev.yaml
  - qa.yaml
  - prd.yaml
  - router-secret-reader-dev.yaml
  - router-secret-reader-qa.yaml
  - router-secret-reader-prd.yaml
