apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-prd
  namespace: prd
spec:
  hard:
    requests.cpu: "64"

    limits.cpu: "128"

    requests.memory: 128Gi

    limits.memory: 256Gi

    pods: "300"

    persistentvolumeclaims: "100"

    requests.storage: 2Ti

    services: "100"

    configmaps: "200"

    secrets: "200"

    count/deployments.apps: "100"

    count/statefulsets.apps: "30"

    count/jobs.batch: "100"

    count/routes.route.openshift.io: "100"