apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa

resources:
  - ../../base
  - certificate.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: todo-redhat
  - path: route-patch.yaml
    target:
      kind: Route
      name: todo-redhat