apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-dev  
  namespace: dev
spec:
  hard:
    requests.cpu: "8"
    limits.cpu: "16"

    requests.memory: 16Gi
    limits.memory: 32Gi

    pods: "80"

    persistentvolumeclaims: "20"
    requests.storage: 200Gi

    services: "40"
    configmaps: "100"
    secrets: "100"

    count/deployments.apps: "50"
    count/statefulsets.apps: "10"
    count/jobs.batch: "50"
    count/cronjobs.batch: "20"
    count/routes.route.openshift.io: "40"
